package com.project.smartinsurance.productService.model.enums;

public enum LineOfBusiness {
    INDIVIDUAL, INDIVIDUAL_LIFE, GROUP_LIFE, CREDIT_LIFE, FUNERAL, HEALTH_MEDICAL, HEALTH_HOSPITAL_CASH,
    MOTOR_PRIVATE, MOTOR_COMMERCIAL, TRAVEL_SINGLE, TRAVEL_ANNUAL, HOME_OWNERS, HOME_CONTENTS,
    MARINE_CARGO, MARINE_HULL, LIABILITY_PUBLIC, LIABILITY_PROFESSIONAL, LIABILITY_PRODUCT,
    WORKERS_COMPENSATION, PERSONAL_ACCIDENT, CRITICAL_ILLNESS, INCOME_PROTECTION,
    MICRO_INSURANCE, ANNUITY, PENSION, INVESTMENT_LINKED
}