package com.project.smartinsurance.claimsService.model.enums;

public enum ClaimStatus {
    INTIMATED, REGISTERED, UNDER_VERIFICATION, DOCS_PENDING, UNDER_INVESTIGATION,
    SURVEY_PENDING, MEDICAL_REVIEW, PENDING_APPROVAL, APPROVED, REJECTED,
    SETTLED, PAID, CLOSED, REOPENED, ON_HOLD, LITIGATION
}
